# Repaint a block copolymer chain

#### Length 80, Goal is 1:2:1 = 10:60:10

In [45]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## 0. Sort by atom ID in OVITO, export sorted data file

## 1. Find atom section in data file

In [46]:
# find the line numbers of key sections
with open("sorted_tetrablock_data", 'r') as f:
    lines = f.readlines()

atoms_start = next(i for i, l in enumerate(lines) if l.strip() == 'Atoms  # molecular') + 1
velocities_start = next(i for i, l in enumerate(lines) if l.strip() == 'Velocities')

print(f"Atoms section starts at line: {atoms_start}")
print(f"Velocities section starts at line: {velocities_start}")

Atoms section starts at line: 21
Velocities section starts at line: 502903

## 2. Load atom section of datafile

In [47]:
headers = ['atom_id','mol_id','atom_type','x','y','z','ix','iy','iz']
df = pd.read_csv("sorted_tetrablock_data", names=headers, 
                 skiprows=atoms_start, 
                 nrows=velocities_start - atoms_start-2,  # -1 for the blank line
                 delimiter=' ')
print(len(df))
df

502880

,atom_id,mol_id,atom_type,x,y,z,ix,iy,iz
0,1,1,2,-26.688946,-43.735604,-7.454141,0,0,0
1,2,1,2,-26.919139,-42.915477,-7.123054,0,0,0
2,3,1,2,-27.023133,-42.772666,-6.156884,0,0,0
3,4,1,2,-27.297848,-43.116130,-5.146881,0,0,0
4,5,1,2,-26.384834,-43.137022,-4.702749,0,0,0
...,...,...,...,...,...,...,...,...,...
502875,502876,6286,3,37.576487,70.557047,36.798576,0,0,0
502876,502877,6286,3,37.770137,70.484896,35.825556,0,0,0
502877,502878,6286,3,37.448169,69.546257,36.272191,0,0,0
502878,502879,6286,3,37.836446,69.615694,35.346278,0,0,0
502879,502880,6286,3,38.809526,70.051562,35.606358,0,0,0

## 3. Calculate atom ID on a chain (1-80) and assign new types

In [48]:
df['id_by_chain']=((df['atom_id']-1) % 80)+1
id_by_chain = df['id_by_chain']
mask_type1 = (10 < id_by_chain) & (id_by_chain<= 70)
mask_type2 = ((1 <= id_by_chain) & (id_by_chain <= 10) | (70 < id_by_chain) & (id_by_chain <= 80))

In [49]:
type_list = []
type_list = np.select([mask_type1, mask_type2], [1, 2], default=0)
df['new_type'] = type_list

pd.set_option('display.max_rows', 200)
print('Print first 2 chains:')
df.head(160)

Print first 2 chains:

,atom_id,mol_id,atom_type,x,y,z,ix,iy,iz,id_by_chain,new_type
0,1,1,2,-26.688946,-43.735604,-7.454141,0,0,0,1,2
1,2,1,2,-26.919139,-42.915477,-7.123054,0,0,0,2,2
2,3,1,2,-27.023133,-42.772666,-6.156884,0,0,0,3,2
3,4,1,2,-27.297848,-43.116130,-5.146881,0,0,0,4,2
4,5,1,2,-26.384834,-43.137022,-4.702749,0,0,0,5,2
5,6,1,2,-26.004341,-43.134393,-3.760781,0,0,0,6,2
6,7,1,2,-25.388809,-43.906126,-3.191778,0,0,0,7,2
7,8,1,2,-24.502743,-43.603821,-2.699913,0,0,0,8,2
8,9,1,2,-24.313830,-44.426328,-2.288319,0,0,0,9,2
9,10,1,2,-23.672540,-43.699649,-2.103704,0,0,0,10,2
10,11,1,2,-24.168606,-44.076310,-1.376580,0,0,0,11,1
11,12,1,2,-24.705833,-43.265783,-1.094668,0,0,0,12,1
12,13,1,2,-25.304010,-43.849113,-2.009624,0,0,0,13,1
13,14,1,2,-26.012150,-44.526849,-1.828076,0,0,0,14,1
14,15,1,2,-26.590867,-43.629267,-1.809190,0,0,0,15,1
15,16,1,2,-26.658688,-42.453618,-1.438165,0,0,0,16,1
16,17,1,2,-27.540994,-42.901207,-1.481473,0,0,0,17,1
17,18,1,2,-27.435218,-43.435451,-2.321657,0,0,0,18,1
18,19,1,2,-26.661966,-43.562332,-2.926938,0,0,0,19,1
19,20,1,2,-27.072939,-43.638027,-3.881485,0,0,0,20,1
20,21,1,1,-27.115529,-44.090841,-4.889200,0,0,0,21,1
21,22,1,1,-26.663401,-44.858126,-4.447060,0,0,0,22,1
22,23,1,1,-26.807473,-45.714386,-4.102549,0,0,0,23,1
23,24,1,1,-25.722051,-46.144500,-4.379509,0,0,0,24,1
24,25,1,1,-26.614413,-46.688622,-4.539698,0,0,0,25,1
25,26,1,1,-27.074675,-47.456032,-4.934655,0,0,0,26,1
26,27,1,1,-26.777393,-48.597988,-4.488577,0,0,0,27,1
27,28,1,1,-26.515417,-48.216057,-3.637992,0,0,0,28,1
28,29,1,1,-27.234344,-48.588579,-3.082193,0,0,0,29,1
29,30,1,1,-26.682130,-49.319821,-2.903069,0,0,0,30,1
30,31,1,1,-26.139434,-49.279728,-3.820220,0,0,0,31,1
31,32,1,1,-25.708647,-50.207487,-3.674602,0,0,0,32,1
32,33,1,1,-24.640495,-50.135336,-3.072981,0,0,0,33,1
33,34,1,1,-25.474087,-49.594432,-2.919547,0,0,0,34,1
34,35,1,1,-24.570174,-49.161036,-2.682105,0,0,0,35,1
35,36,1,1,-25.102412,-48.463802,-3.157177,0,0,0,36,1
36,37,1,1,-24.949552,-47.579130,-2.742213,0,0,0,37,1
37,38,1,1,-25.276444,-47.633194,-3.858208,0,0,0,38,1
38,39,1,1,-24.555477,-48.331672,-3.941877,0,0,0,39,1
39,40,1,1,-23.886860,-48.499972,-3.333515,0,0,0,40,1
40,41,1,1,-22.985516,-48.725476,-3.598443,0,0,0,41,1
41,42,1,1,-22.902710,-47.595117,-3.223999,0,0,0,42,1
42,43,1,1,-23.084382,-46.544967,-2.990730,0,0,0,43,1
43,44,1,1,-23.096143,-45.783513,-2.327667,0,0,0,44,1
44,45,1,2,-23.332581,-44.860087,-2.125038,0,0,0,45,1
45,46,1,2,-22.652740,-44.202265,-2.487947,0,0,0,46,1
46,47,1,2,-22.366438,-44.314930,-3.644586,0,0,0,47,1
47,48,1,2,-22.809972,-43.394298,-4.116084,0,0,0,48,1
48,49,1,2,-23.058632,-42.723251,-4.643244,0,0,0,49,1
49,50,1,2,-22.224929,-42.296710,-4.649281,0,0,0,50,1
50,51,1,2,-21.356684,-42.157474,-4.272740,0,0,0,51,1
51,52,1,2,-20.403653,-41.840047,-3.801188,0,0,0,52,1
52,53,1,2,-21.155406,-42.590114,-3.337652,0,0,0,53,1
53,54,1,2,-21.391987,-41.721834,-2.938858,0,0,0,54,1
54,55,1,2,-21.815649,-41.046352,-2.493271,0,0,0,55,1
55,56,1,2,-21.799435,-41.457252,-1.648010,0,0,0,56,1
56,57,1,2,-20.899021,-41.214521,-1.883032,0,0,0,57,1
57,58,1,2,-21.002759,-40.331351,-2.444807,0,0,0,58,1
58,59,1,2,-20.589103,-40.399257,-1.449333,0,0,0,59,1
59,60,1,2,-19.899234,-40.441181,-2.079163,0,0,0,60,1
60,61,1,2,-18.988639,-40.097042,-2.097061,0,0,0,61,1
61,62,1,2,-19.437468,-40.480341,-3.030264,0,0,0,62,1
62,63,1,2,-20.107305,-40.833596,-3.784631,0,0,0,63,1
63,64,1,2,-19.658568,-40.156666,-4.290472,0,0,0,64,1
64,65,1,3,-19.129115,-39.412884,-4.700180,0,0,0,65,1
65,66,1,3,-19.735957,-38.672274,-4.547992,0,0,0,66,1
66,67,1,3,-20.592600,-39.192124,-4.461096,0,0,0,67,1
67,68,1,3,-20.735136,-38.309408,-3.953133,0,0,0,68,1
68,69,1,3,-19.908762,-37.783408,-4.036520,0,0,0,69,1
69,70,1,3,-19.411631,-37.023751,-4.462952,0,0,0,70,1
70,71,1,3,-18.542028,-36.624243,-4.611949,0,0,0,71,2
71,72,1,3,-18.347792,-35.668651,-4.817367,0,0,0,72,2
72,73,1,3,-18.373431,-35.029063,-5.562159,0,0,0,73,2
73,74,1,3,-18.717283,-34.989488,-6.487995,0,0,0,74,2
74,75,1,3,-19.355639,-34.515215,-7.051503,0,0,0,75,2
75,76,1,3,-19.898610,-34.436969,-6.250534,0,0,0,76,2
76,77,1,3,-20.056351,-34.694806,-5.268746,0,0,0,77,2
77,78,1,3,-19.365716,-35.385887,-5.746574,0,0,0,78,2
78,79,1,3,-19.393545,-35.961203,-6.498993,0,0,0,79,2
79,80,1,3,-19.830883,-35.453048,-7.216608,0,0,0,80,2
80,81,2,2,-26.517818,-43.608878,2.889979,0,0,0,1,2
81,82,2,2,-25.872378,-43.861917,3.565826,0,0,0,2,2
82,83,2,2,-25.911095,-42.961098,4.010887,0,0,0,3,2
83,84,2,2,-26.434879,-42.660647,3.175244,0,0,0,4,2
84,85,2,2,-27.347002,-42.370307,3.752802,0,0,0,5,2
85,86,2,2,-26.540061,-42.021279,4.048640,0,0,0,6,2
86,87,2,2,-26.893959,-42.468034,4.798000,0,0,0,7,2
87,88,2,2,-26.473538,-42.561097,5.693033,0,0,0,8,2
88,89,2,2,-26.627404,-43.108625,6.427004,0,0,0,9,2
89,90,2,2,-27.235957,-42.214129,6.401697,0,0,0,10,2
90,91,2,2,-27.333744,-41.272090,6.866951,0,0,0,11,1
91,92,2,2,-26.485463,-41.165454,6.463280,0,0,0,12,1
92,93,2,2,-25.534015,-41.570129,6.432475,0,0,0,13,1
93,94,2,2,-25.615504,-42.557942,6.335551,0,0,0,14,1
94,95,2,2,-26.001187,-43.494162,5.750506,0,0,0,15,1
95,96,2,2,-25.541550,-43.709864,6.761903,0,0,0,16,1
96,97,2,2,-26.034852,-43.077184,7.242262,0,0,0,17,1
97,98,2,2,-26.406713,-42.184073,7.053698,0,0,0,18,1
98,99,2,2,-27.059084,-42.842696,7.536206,0,0,0,19,1
99,100,2,2,-27.738019,-43.096287,6.802102,0,0,0,20,1
100,101,2,1,-28.132246,-43.865898,6.376021,0,0,0,21,1
101,102,2,1,-28.829432,-44.514388,6.687797,0,0,0,22,1
102,103,2,1,-29.018530,-45.464095,6.591978,0,0,0,23,1
103,104,2,1,-29.913431,-45.753146,6.741694,0,0,0,24,1
104,105,2,1,-30.608811,-45.038552,6.923484,0,0,0,25,1
105,106,2,1,-30.861774,-45.673194,5.772813,0,0,0,26,1
106,107,2,1,-31.355802,-45.945919,4.913851,0,0,0,27,1
107,108,2,1,-31.465411,-46.931096,5.402180,0,0,0,28,1
108,109,2,1,-30.279346,-46.726080,5.636979,0,0,0,29,1
109,110,2,1,-30.362242,-46.241088,4.649414,0,0,0,30,1
110,111,2,1,-30.591646,-47.258573,4.312087,0,0,0,31,1
111,112,2,1,-29.676410,-46.971309,4.698879,0,0,0,32,1
112,113,2,1,-28.882754,-47.833291,4.647519,0,0,0,33,1
113,114,2,1,-28.675401,-47.079201,5.536773,0,0,0,34,1
114,115,2,1,-28.751116,-46.798021,6.528298,0,0,0,35,1
115,116,2,1,-28.612432,-47.791180,7.085544,0,0,0,36,1
116,117,2,1,-28.208143,-48.341154,6.205611,0,0,0,37,1
117,118,2,1,-27.837262,-47.386728,6.126458,0,0,0,38,1
118,119,2,1,-27.330836,-46.725425,6.754740,0,0,0,39,1
119,120,2,1,-26.594836,-46.169355,6.458403,0,0,0,40,1
120,121,2,1,-26.145087,-45.223836,7.050955,0,0,0,41,1
121,122,2,1,-25.664243,-45.388064,6.186451,0,0,0,42,1
122,123,2,1,-24.757872,-45.563242,6.480431,0,0,0,43,1
123,124,2,1,-24.193839,-44.892309,6.021178,0,0,0,44,1
124,125,2,2,-25.124731,-44.484191,6.198480,0,0,0,45,1
125,126,2,2,-24.539975,-44.154919,6.928538,0,0,0,46,1
126,127,2,2,-24.566006,-43.479295,7.617398,0,0,0,47,1
127,128,2,2,-23.546392,-43.729885,7.471251,0,0,0,48,1
128,129,2,2,-23.332665,-44.464167,6.866726,0,0,0,49,1
129,130,2,2,-23.467128,-45.350572,6.555260,0,0,0,50,1
130,131,2,2,-22.810325,-46.067090,6.703267,0,0,0,51,1
131,132,2,2,-22.345409,-46.659601,6.196937,0,0,0,52,1
132,133,2,2,-22.351776,-45.746900,5.737278,0,0,0,53,1
133,134,2,2,-21.720466,-45.161448,6.092264,0,0,0,54,1
134,135,2,2,-21.913215,-44.153938,6.421208,0,0,0,55,1
135,136,2,2,-20.953585,-44.196810,6.471726,0,0,0,56,1
136,137,2,2,-20.240595,-43.571702,6.818160,0,0,0,57,1
137,138,2,2,-19.252584,-43.345770,7.081896,0,0,0,58,1
138,139,2,2,-18.413869,-43.292304,6.534661,0,0,0,59,1
139,140,2,2,-17.389798,-43.289895,6.528925,0,0,0,60,1
140,141,2,2,-17.779396,-42.369355,6.875282,0,0,0,61,1
141,142,2,2,-18.575597,-41.852870,7.215436,0,0,0,62,1
142,143,2,2,-18.816761,-41.319147,8.184565,0,0,0,63,1
143,144,2,2,-18.476707,-40.523498,8.574592,0,0,0,64,1
144,145,2,3,-18.328318,-39.653744,8.146283,0,0,0,65,1
145,146,2,3,-18.109119,-39.136788,9.031714,0,0,0,66,1
146,147,2,3,-17.917165,-38.241380,8.805182,0,0,0,67,1
147,148,2,3,-18.002476,-38.082625,7.792559,0,0,0,68,1
148,149,2,3,-18.739199,-38.575901,8.225091,0,0,0,69,1
149,150,2,3,-19.008860,-37.696385,7.761302,0,0,0,70,1
150,151,2,3,-18.842437,-36.781804,7.889915,0,0,0,71,2
151,152,2,3,-18.973363,-35.900945,8.459848,0,0,0,72,2
152,153,2,3,-19.889394,-35.578004,8.604695,0,0,0,73,2
153,154,2,3,-20.080626,-34.655314,8.744533,0,0,0,74,2
154,155,2,3,-20.451033,-34.651084,9.735714,0,0,0,75,2
155,156,2,3,-19.502603,-34.681875,9.712907,0,0,0,76,2
156,157,2,3,-18.486178,-34.647033,9.806453,0,0,0,77,2
157,158,2,3,-18.874823,-34.199513,10.559115,0,0,0,78,2
158,159,2,3,-19.328034,-33.284858,10.780001,0,0,0,79,2
159,160,2,3,-19.338978,-33.959164,11.492399,0,0,0,80,2

## 4. Replace old type with new type, add header and tail, and write to new file

In [50]:
df['atom_type'] = df['new_type']

# read the original header and everything from velocity
with open("sorted_tetrablock_data", 'r') as f:
    lines = f.readlines()

header_lines = lines[:atoms_start]
tail = lines[velocities_start-1:]

# write header + modified atoms + tail
with open("repainted_sorted_tetrablock_data", 'w') as f:
    f.writelines(header_lines)
    df[['atom_id','mol_id','atom_type','x','y','z','ix','iy','iz']].to_csv(
        f, sep=' ', index=False, header=False
    )
    f.writelines(tail)

print(repr(lines[velocities_start]))    # should be 'Velocities\n'
print(repr(lines[velocities_start-1]))  # should be '\n' (blank line)

'Velocities\n'
'\n'